// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqbvbxiflbczygahkoyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxYnZieGlmbGJjenlnYWhrb3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NTgyNzgsImV4cCI6MjA3MjEzNDI3OH0.5HM6CJbf4LxB5VvmEH1RaLQy-XgZ7pEgWr_dOLPcSdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});